export const People = [
  { name: "Yamisuri Hurtado", email: "yamisuri0911@gmail.com" },
  { name: "Martha Berrio", email: "genardberrio@gmail.com" },
  { name: "Jose Danilo Chantrez Montaño", email: "genardberrio@gmail.com" },
  { name: "Alexis de Jesus Rivera", email: "angelicadelvalle155@gmail.com" },
  { name: "Anyi Karina Carrillo Guerra", email: "angikarelis@gmail.com" },
  { name: "Geraldin Alzate Morales", email: "geralalzate.24@gmail.com" },
  { name: "Emanuel Eugenio De Leon Pinzon", email: "Emanuel.deleon01@gmail.com" },
  { name: "german peña santos", email: "germanpsantos@gmail.com" },
  { name: "Victor Hugo Hernandez", email: "victorhugohr1@hotmail.com" },
  { name: "ELIOTY GIUSEPPE REYES CARANZA", email: "giusseppereyes@yahoo.com" },
  { name: "Alexander Romano Ramírez", email: "alexromano07@gmail.com" },
  { name: "Alveiro Gómez Téllez", email: "johangomezt20@gmail.com" },
  { name: "Ludwing Francisco Gomez Almeida", email: "ludwingfrancisco@gmail.com" },
  { name: "Nicolas Elias Castro Trujillo", email: "notienecorreo@gmail.com" },
  { name: "Yenny Zamira Valencia", email: "zamiravalencia90@gmail.com" },
  { name: "Daniel Lopez", email: "michaeldaniellopez@gmail.com" },
  { name: "edwin palacios arboleda", email: "edwinchechi1904@gmail.com" },
  { name: "Victor Raul Diaz Gallego", email: "victordiaz426@gmail.com" },
  { name: "Mateo Ocampo", email: "mateo9535@icloud.com" },
  { name: "Katherine Agudelo Ayala", email: "victordiaz426@gmail.com" },
  { name: "Maria Camila Franco Cuartas", email: "mateo9535@icloud.com" },
  { name: "Jose Miguel Cuero", email: "iamsebastiancuerocanelo@hotmail.com" },
  { name: "Diego Alonso Pinzon Meza", email: "dialpi2000@gmail.com" },
  { name: "Lina Maria Rodas Gomez", email: "rodaslinamaria@gmail.com" },
  { name: "Arley Palacios Timagenes", email: "Leimarelaz@gmail.com" },
  { name: "Gabriela Stefany Estevez de Brazoban", email: "notienecorreo@gmail.com" },
  { name: "Yocasta Villa Cruz", email: "candyvilla1618@icloud.com" },
  { name: "Marly Julieth Perez Suarez", email: "staylorel85@yahoo.com" },
  { name: "Yarellis Patricia Fabra García", email: "fabrayarelis221@gmail.com" },
  { name: "Luz Marina Juanes", email: "Luz08juanes@gmil.com" },
  { name: "Juan Pablo Zuluaga Duque", email: "pabloduque122002@gmail.com" },
  { name: "Fabian Andres Rodriguez Ulloa", email: "skypelanas@gmail.com" },
  { name: "Josue David Molina Sabillon", email: "josuedaivi@gmail.com" },
  { name: "Tatiana Muñoz Velez", email: "skypelanas@gmail.com" },
  { name: "Yaneth Peña Ceballos", email: "edwin@gmail.com" },
  { name: "Rubén Darío Páez Sánchez", email: "rubenperez@gmail.com" },
  { name: "Nikolay Nikolaevich Tsybikov", email: "igogotrucking@gmail.com" },
  { name: "Joselyn Perez Sevilla", email: "joselynp06edg@gmail.com" },
  { name: "Melanie Martinez", email: "mela.nie.2906199@gmail.com" },
  { name: "Mc Ella Lever Alexis Aurelio", email: "alexismc27@gmail.com" },
  { name: "Norlan Patricia Mejia Ramirez", email: "norlanmejia0914@gmail.com" },
  { name: "juan fernando barcenas arango", email: "Juanferbarcenas@gmail.com" },
  { name: "Miguel Funes", email: "funesma@gmail.com" },
  { name: "Juan Alvarado", email: "Junaldro1@hotmail.com" },
  { name: "Laura Daniela Gonzalez", email: "lauradanielags289@hotmail.com" },
  { name: "Zulma Rocío Romero Leal", email: "zulma.romero@cnmh.gov.co" },
  { name: "Nancy Yadira Arenas Rivera", email: "nancyarenasrivera4@gmail.com" },
  { name: "Laura Escobar", email: "lauraa.escobarg@gmail.com" },
  { name: "Yeimi Xiomara Pérez Galindo", email: "xiomaraperez094@gmail.com" },
  { name: "María Alejandra Vargas Corredor", email: "maria.vargas@cnmh.gov.co" },
  { name: "Aleida Amparo Muñoz Londoño", email: "aleidamunoz1008@gmail.com" },
  { name: "Oscar Eduardo Morocho Cuji", email: "eduardo-bsc@hotmail.com" },
  { name: "Sthepanie kate Dallimore", email: "jsdallim@gmail.com" },
  { name: "Wendy Yariany Carrillo Guzman", email: "jorgeivanmc@gmail.com" },
  { name: "Claudia Rodriguez", email: "crrodriguez2020@outlook.com" },
  { name: "Julian Esteban Fernandez Molina", email: "fjulianesteban@gmail.com" },
  { name: "Valentina Moncada Correa", email: "Valenmoncada310809@gamil.com" },
  { name: "Luis Fernando Ortiz Velez", email: "luisortizvelez258@gmail.com" },
  { name: "Wilfredo Insuasti Mejia", email: "wilime1077@gmail.com" },
  { name: "Valeria Marín", email: "valemarin0302@gmail.com" },
  { name: "SABAJON APOLO S.A.S", email: "info@sabajonapolo.com.co" },
  { name: "IMPORT SYSTEM SISTEMAS Y SUMINISTROS S.A.S.", email: "facturacion@importsystem.com.co" },
  { name: "Jaqueline Parra Ortiz", email: "jparra@sabajonapolo.com.co" },
  { name: "Gustavo", email: "comercial@10esas.com" },
  { name: "Rolando Guerrero", email: "Rolando22_@outlook.com" },
  { name: "Santiago Castillo", email: "castillosernawk@gmail.com" },
  { name: "Carlos", email: "carlosacardenasp@gmail.com" },
   { name: "Camila lugo", email: "camilalugo847@gmail.com" }
];
